script:
- docker build --target test --tag my-test-image .
- docker run my-test-image todo_app/test_app.py
- docker run my-test-image todo_app/test_ViewModel.py
- docker run my-test-image todo_app/e2etests
env:
  global:
    secure: Mvt81ck3ZQH43Mb80IUdywulrdK/3+C2zRli0418KfNYdsNJWzzTesCmoik5ZuKf7oKAGj2UGPfNQfkB7iNIqFMl3YA9Yx2rPu7kmYHsYRi3dvHjNDiPXNomxcbZ32XsNwLPmwABxHMvP531vchI3qtBACx57q8IRj1E69YgbrwuIUeLAqgEOUHPojgzrEMcixwil/nLSsXDbtIg5+oorwhnKWWBQkxRopYW3i56lmbePwMz0Hf1SaCssDzj9U0XrfZdMndfQie//euv92cSTrnkUFpYk+7P68C1Tcn7Xue4nqbg179H7fUN5v26O7b40Tm4TEuPwigVPmzqXbl5ZsjCJ+tu930skRsP6f1PuV1YaXD1CjvPblFeLrj2fR7H02BLAP2RMQvM1fe9uVlO7+H0SHtkxywqU27X17fW00XJVcl4Gb1/JPYHX+L+TJNBgQ30aJXkvVK4gbWo8NlY7drEMk3T+mL9s9ZQh0UpefqCjNIrgnmLfiuTzEieDHKiB6DnlknIXWof/4rbMtjxfFQutpYe3Vy6b4f0OqW0oAIbR0AlEppTTtnKpHr0eC2/DfvgJzGJDRu6nvJiI14A4qN7hRioBZnrzIsYdLX/6kcY4JSzTkzqgSc0+/0cMVQh3kdwg8PCYVNsg4Z5Qy7zBb1f9Y3uj2TT9fSDnXpDALQ=
